export const ROADS = {
    HIGHWAY: 1,
    PROVINCIAL: 2,
    URBAN: 3
};

export const BRANCH_ANGLE_LIMIT = 3;
export const FORWARD_ANGLE_LIMIT = 15;
export const HIGHWAY_BRANCH_POPULATION_THRESHOLD = 0.1;
export const DEFAULT_BRANCH_PROBABILITY = 0.4;
export const HIGHWAY_BRANCH_PROBABILITY = 0.05;
export const DEFAULT_SEGMENT_LENGTH = 300;
export const HIGHWAY_SEGMENT_LENGTH = 400;
export const DEFAULT_SEGMENT_WIDTH = 6;
export const HIGHWAY_SEGMENT_WIDTH = 16;
export const URBAN_BRANCH_POPULATION_THRESHOLD =  0.1;